#baseURL = 'http://localhost:1313/'
baseURL = 'https://spud-online.netlify.app/'
languageCode = 'en-gb'
title = 'SPUD'
theme = 'PaperMod'

[params]
  dateFormat = '2 January 2006'

[contentTypes]
  ['text/html'] = ['html']
